version: '3'

services:
    redis:
      image: redis:latest
      container_name: redis_broker
      ports:
        - "6379:6379"
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sonus_worker_api
        command: python app.py
        restart: always
        ports:
            - "5000:5000"
        depends_on:
            - redis
    worker:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: celery_worker    
        command: celery -A worker.celery worker --pool threads --loglevel=info
        volumes:
            - .:/app/
        depends_on:
            - redis    